# name: GitHub Actions & Docker deployment demo
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
# on: [push]
# jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         name: Check out code
    
#       - name: Build & push Docker image
#         uses: mr-smithers-excellent/docker-build-push@v4
#         with:
#           image: yha7/myrepo
#           registry: docker.io
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
